name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]  # Asegúrate que diga master (no main)
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Docker
        run: |
          docker build -t app .
          docker create --name app-container app
          docker cp app-container:/usr/share/nginx/html ./site
          docker rm app-container
      - uses: peaceiris/actions-gh-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
