name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build with Docker
        run: |
          docker build -t app .
          docker create --name app-container app
          docker cp app-container:/usr/share/nginx/html ./site
          docker rm app-container

      - name: Setup Pages
        uses: actions/configure-pages@v4  # Actualizado a v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Versión actualizada
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # Actualizado a v4
